version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  elastic:
    image: elasticsearch:7.17.5
    environment:
      ES_JAVA_OPTS: "-Xms200m -Xmx200m"
      discovery.type: single-node
    ports:
      - '9200:9200'

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always

  etl_genres_pipeline:
      build: 
        context: etl/
        dockerfile: genres.Dockerfile
      depends_on:
        - postgres
        - elastic
      env_file:
        - .env

  etl_persons_pipeline:
      build: 
        context: etl/
        dockerfile: persons.Dockerfile
      depends_on:
        - postgres
        - elastic
      env_file:
        - .env

  etl_filmwork_pipeline:
      build: 
        context: etl/
        dockerfile: film_works.Dockerfile
      depends_on:
        - postgres
        - elastic
      env_file:
        - .env

  api_service:
      build: 
        context: fastapi-solution/
        dockerfile: Dockerfile
      depends_on:
        - redis
        - elastic
      env_file:
        - .env
      restart: always
      ports:
        - "8000:80"
volumes:
  esdata: